server:
  port: 8086
spring:
  data:
    mongodb:
      host: 3.7.2.2
      port: 27017
      database: chat
  application:
    name: chat-service
  cloud:
    config:
      uri: http://3.7.2.2:8888
      import-check.enabled: false
management:
  security:
    enabled: false
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://3.7.2.2:8761/eureka
